---
- name: Change EBS Volume Type from gp2 to gp3
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get EBS volume ID using AWS CLI
      command: >
        aws ec2 describe-volumes --filters "Name=tag:elasticbeanstalk:environment-name,Values={{ environment_name }}" --query "Volumes[*].VolumeId" --output text --region "{{ region }}"
      register: volumes_info

    - name: Modify EBS volume to gp3 using AWS CLI
      command: >
        aws ec2 modify-volume --volume-id {{ item }} --volume-type gp3 --region "{{ region }}"
      loop: "{{ volumes_info.stdout_lines }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
