---
- name: Enable Immutable Updates and Change Instance Type for Elastic Beanstalk Environment
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Enable Immutable Deployment Policy using AWS CLI
      command: >
        aws elasticbeanstalk update-environment
        --application-name "{{ application_name }}"
        --environment-name "{{ environment_name }}"
        --option-settings Namespace=aws:elasticbeanstalk:command,OptionName=DeploymentPolicy,Value=Immutable
        --region "{{ region }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Wait for Environment to be Ready after Immutable Deployment Policy Change
      command: |
        aws elasticbeanstalk describe-environments --application-name "{{ application_name }}" \
        --environment-names "{{ environment_name }}" --query 'Environments[0].Status' --output text --region "{{ region }}"
      register: env_status
      until: env_status.stdout == "Ready"
      retries: 30
      delay: 60

    - name: Change Instance Type using AWS CLI
      command: >
        aws elasticbeanstalk update-environment
        --application-name "{{ application_name }}"
        --environment-name "{{ environment_name }}"
        --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,Value=t3.medium
        --region "{{ region }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Wait for Environment to be Ready after Instance Type Change
      command: |
        aws elasticbeanstalk describe-environments --application-name "{{ application_name }}" \
        --environment-names "{{ environment_name }}" --query 'Environments[0].Status' --output text --region "{{ region }}"
      register: env_status
      until: env_status.stdout == "Ready"
      retries: 30
      delay: 60
